name: Docker Image Build

on:
  push:
    branches:
      - 'main'
      - 'build/*'
    tags:
      - 'v*'

env:
  REGISTRY: projects.registry.vmware.com
  PROJECT: build_inspector
  IMAGE_NAME: build-inspector

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Build and Push Main
      id: build-and-push-main
      uses: docker/build-push-action@v2
      if: ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref_name, 'build/')
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.PROJECT}}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.PROJECT}}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
    - name: Build and Push Tag
      id: build-and-push-tags
      uses: docker/build-push-action@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.PROJECT}}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.PROJECT}}/${{ env.IMAGE_NAME }}:${{ github.github.ref_name }},